# Generated by Django 5.0.7 on 2024-08-01 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo_task',
            name='task_completed',
            field=models.DateField(blank=True, null=True),
        ),
    ]
